Appease pylint
No functional changes in this commit.

Fix the following pylint complaint.

ERROR: plugins/module_utils/vrf/dcnm_vrf_v12.py:1289:20: logging-fstring-interpolation: Use lazy % formatting in logging functions