antsibull-docs generated doc fails rstcheck
Need to ping Mike to remember how we generate docs...

ERROR: docs/cisco.dcnm.dcnm_image_policy_module.rst:37:0: Unknown directive type "rst-class".