dcnm_interface: This is failing sanity due to pulling develop
This seems to have made it into my working branch :-(

Deleting these for now so that YAML sanity passes.

Will figure out a solution later, probably just copy the legit dcnm_interface.py from develop?

ERROR: plugins/modules/dcnm_interface.py:136:11: key-duplicates: DOCUMENTATION: duplication of key "native_vlan" in mapping
ERROR: plugins/modules/dcnm_interface.py:490:11: key-duplicates: DOCUMENTATION: duplication of key "native_vlan" in mapping