BootflashFiles() address tech debt (#555)
* BootflashFiles: address tech debt

This commit addresses tech debt in class BootflashFile.

The main changes are:

- Remove class decorators in favor of class properties
- Simplify logic in refresh_switch_details
- Update unit-tests to align with changes

Details

1. Remove class decorators

1a. Properties.add_rest_send
1b. Properties.add_results

2. Remove import for Properties

3. Add class properties for RestSend and Results

4. Import Results and RestSend for use in validation in their respective properties

5. import Typing.Literal for use in rest_send and results properties.

6. BootflashFiles.refresh_switch_details

6a. Diff lines 150-168, because rest_send validation occurs in the setter and getter, we can remove validation from refresh_switch_details and simplify this method.

7. test_bootflash_files.py

7a. test_bootflash_files_00000

- add asserts for rest_send and results

7b. test_bootflash_files_00100

- modify assert for earlier validation of rest_send

7c. test_bootflash_files_00110. modify assert for earlier validation of rest_send

7c. test_bootflash_files_00120. Remove. Results() is now initialized in BootflashFiles.__init__()

* UT: Appease linters

No functional changes in this commit.

1. Add pylint directive to suppress invalid-name

2 black reformating lines for more relaxed line length

* UT: Update copyright dates

No functional changs in this commit.

* BootflashFiles: Appease linters

No functional changes in this commit

1. Add pylint directive to suppress invalid-name

2 black reformating lines for more relaxed line length

* BootflashFiles: type-hints, validation hardening

1. Add type-hints

2. Add two methods to verify proper instantiation of rest_send and switch_details

- _rest_send_instantiated
- _switch_details_instantiated

3. add_file_to_existing_payload

- Simplify logic

4. test_bootflash_files.py

- Update all unit tests to reflect changes to BootflashFiles.

- Some unit-tests started to fail because item 2 improved detection of improperly-validated RestSend and SwitchDetails.  These tests were fixed.  Mainly this had to do with switch_details.rest_send not being set.

* Appease black and sanity linters

Fix the below sanity error by running through the black linter:

ERROR: plugins/module_utils/bootflash/bootflash_files.py:464:5: E129: visually indented line with same indent as next logical line

* RestSend must be passed to SwitchDetails

1. Recent changes to SwitchDetails exposed weakness in the unit tests in that the tests would pass without having passed an instance of RestSend to SwitchDetails.

This commit updates the following two unit tests to pass RestSend to SwitchDetails.

test_bootflash_deleted_03200
test_bootflash_deleted_03210

2. DcnmBootflash.Deleted

- Need to pass RestSend instance to BootflashInfo.SwitchDetails
- Need to pass Results instance to BootflashInfo.SwitchDetails
- Need to pass RestSend instance to BootflashFiles.SwitchDetails