Appease pylint and add TODOs
1. plugins/module_utils/image_upgrade/image_upgrade.py

1a. Fix the below errors by importing annotations from __future__:

ERROR: Found 2 pylint issue(s) which need to be resolved:
ERROR: plugins/module_utils/image_upgrade/image_upgrade.py:888:29: unsupported-binary-operation: unsupported operand type(s) for |
ERROR: plugins/module_utils/image_upgrade/image_upgrade.py:899:33: unsupported-binary-operation: unsupported operand type(s) for |

1b. Add the following TODOs

        # TODO: device does not contain policy, or upgrade keys.  It contains only ip_address key. Revisit this!
        # TODO: install_options.nxos property does not exist.  Revisit this!